<div class="container-fluid h-100">
	<div class="row h-100">
    
    <div class="col-md-6 banner">
    	<div class="row h-100 justify-content-center align-items-center">
				<div class="communicationItem">
                    <img src="/img/biblioteca.jpg" />
				</div>
		</div>
    </div>

    <div class="col-md-6 pt-4 pl-5 pr-5">


		<div class="row pt-5 pl-5 pr-5">
			<div class="col pl-5 pr-5">
				<h1 class="title">Sua Biblioteca, Sua História: Descubra, Aprenda, Cresça</h1>

				<h2 class="mt-5 subtitle">Login</h2>
			</div>
		</div>

        <form method="POST" action="/autenticar">
            <div class="row">
                <div class="col">
                    <input type="email" class="form-control" name="email" placeholder="E-mail">
                    <input type="password" class="form-control mt-4" name="senha" placeholder="Senha">
                </div>
            </div>
                <div class="col-auto">
                    <button type="submit" class="btn btn-primary mt-2">Entrar</button>
                </div>
            <?php if ($this->view->login == 'erro') {?>
                <div class="row">
                    <div class="col">
                        <span class="text text-danger">*E-mail e ou senha invalidos</span>
                    </div>
                </div>
            <?php } ?>
        </form>


    </div>

  </div>
</div>