<?php
$page = basename($_SERVER['REQUEST_URI'], ".php");
?>

<!-- Main Content -->
<section class="content">
    <div class="">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-7 col-md-6 col-sm-12">
                    <h2> <?= $page; ?> </h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="<?= $page ?>"><i class="zmdi zmdi-home"></i> Home</a></li>
                    </ul>
                    <button class="btn btn-primary btn-icon mobile_menu" type="button"><i class="zmdi zmdi-sort-amount-desc"></i></button>
                </div>
                <div class="col-lg-5 col-md-6 col-sm-12">
                    <a href="/sair" class="mega-menu btn btn-danger btn-icon float-right" title="Sair"><i class="zmdi zmdi-power"></i></a>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row">
                <!-- Carrossel -->
                <div class="col-md-4">
                    <div id="imageCarousel" class="carousel slide" data-ride="carousel">
                        <!-- Indicators -->
                        <ol class="carousel-indicators">
                            <li data-target="#imageCarousel" data-slide-to="0" class="active"></li>
                            <li data-target="#imageCarousel" data-slide-to="1"></li>
                            <li data-target="#imageCarousel" data-slide-to="2"></li>
                        </ol>

                        <!-- Carousel items -->
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src="/assets/images/3.jpg" class="d-block w-100 carrossel-img" alt="Image 1">
                                <div class="carousel-caption d-none d-md-block"></div>
                            </div>
                            <div class="carousel-item">
                                <img src="/assets/images/2.jpg" class="d-block w-100 carrossel-img" alt="Image 2">
                                <div class="carousel-caption d-none d-md-block"></div>
                            </div>
                            <div class="carousel-item">
                                <img src="/assets/images/1.jpg" class="d-block w-100 carrossel-img" alt="Image 3">
                                <div class="carousel-caption d-none d-md-block"></div>
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="carousel-control-prev" href="#imageCarousel" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Anterior</span>
                        </a>
                        <a class="carousel-control-next" href="#imageCarousel" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Próximo</span>
                        </a>
                    </div>
                </div>

                <!-- Calendário -->
                <div class="col-md-6 col-lg-8">
                    <div class="card">
                        <div class="body">
                            <div id="calendar"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
