<?php
$page = basename($_SERVER['REQUEST_URI']);
?>
<section class="content">
    <div class="body_scroll">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-7 col-md-6 col-sm-12">
                    <h2> <?= $page; ?> </h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="/home"><i class="zmdi zmdi-home"></i> Home</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="/usuarios"><i class="zmdi zmdi-library"></i> Usuarios</a>
                        </li>
                        <?php if ($_SERVER['REQUEST_URI'] == '/cadastros') : ?>
                            <li class="breadcrumb-item active">Cadastro de Usuarios</li>
                        <?php endif; ?>
                    </ul>
                    <button class="btn btn-primary btn-icon mobile_menu" type="button"><i class="zmdi zmdi-sort-amount-desc"></i></button>
                </div>
                <div class="col-lg-5 col-md-6 col-sm-12">
                    <a href="/sair" class="mega-menu btn btn-danger btn-icon float-right" title="Sair"><i class="zmdi zmdi-power"></i></a>
                </div>
            </div>
        </div>
        <hr>
        <div class="container-fluid">
            <div class="container">
                <div class="d-flex justify-content-center mt-5">
                    <div class="card" style="width: 36rem;">
                        <div class="card-body">

                            <div class="row">
                                <div class="col">

                                    <form action="/registrar" method="post">
                                        <div class="form-group">
                                            <input type="text" class="form-control mb-3" name="nome"  value="<?= $this->view->usuario['nome'] ?>" placeholder="Nome">
                                        </div>

                                        <div class="form-group">
                                            <input type="text" class="form-control mb-3" name="cpf" value="<?= $this->view->usuario['cpf'] ?>" placeholder="CPF">
                                        </div>

                                        <div class="form-group">
                                            <input type="text" class="form-control mb-3" name="email" value="<?= $this->view->usuario['email'] ?>" placeholder="E-mail">
                                        </div>

                                        <div class="form-group">
                                            <input type="password" class="form-control mb-3" name="senha" value="<?= $this->view->usuario['senha'] ?>" placeholder="Senha">
                                        </div>

                                        <div class="form-group">
                                            <select class="w-50" name="tipo_usuario" required>
                                                <option value="">Selecione o tipo de usuário</option>
                                                <option value="aluno" <?= isset($this->view->usuarios['tipo_usuario']) && $this->view->usuarios['tipo_usuario'] === 'aluno' ? 'selected' : '' ?>>Aluno</option>
                                                <option value="professor" <?= isset($this->view->usuarios['tipo_usuario']) && $this->view->usuarios['tipo_usuario'] === 'professor' ? 'selected' : '' ?>>Professor</option>
                                            </select>
                                        </div>


                                        <button type="submit" class="btn btn-success mb-4 w-100" onclick="document.querySelector('form').submit();">Cadastra</button>

                                    </form>
                                    <?php if (isset($this->view->success) && $this->view->success) { ?>
                                        <small class="form-text text-success font-13 font-weight-bold text-center alert-success"><?= $this->view->success ?></small>
                                    <?php } ?>
                                    <?php if (isset($this->view->error) && $this->view->error) { ?>
                                        <small class="form-text text-danger font-13 font-weight-bold text-center alert-danger"><?= $this->view->error ?></small>
                                    <?php } ?>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>





    
  