<?php
$page = basename($_SERVER['REQUEST_URI']);
?>
<!doctype html>
<html class="no-js " lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>Gerenciador de Biblioteca</title>
    <link rel="stylesheet" href="/assets/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/plugins/multi-select/css/multi-select.css">
    <link rel="stylesheet" href="/assets/plugins/jquery-spinner/css/bootstrap-spinner.css">
    <link rel="stylesheet" href="/assets/plugins/bootstrap-tagsinput/bootstrap-tagsinput.css">
    <link rel="stylesheet" href="/assets/plugins/bootstrap-select/css/bootstrap-select.css" />
    <link rel="stylesheet" href="/assets/plugins/nouislider/nouislider.min.css" />
    <link rel="stylesheet" href="/assets/plugins/jvectormap/jquery-jvectormap-2.0.3.min.css"/>
    <link rel="stylesheet" href="/assets/plugins/charts-c3/plugin.css"/>
    <link rel="stylesheet" href="/assets/plugins/select2/select2.css" />
    <link rel="stylesheet" href="assets/plugins/fullcalendar/fullcalendar.min.css">

    <link rel="stylesheet" href="/assets/plugins/morrisjs/morris.min.css" />
    <!-- Custom Css -->
    <link rel="stylesheet" href="/assets/css/style.min.css">
    <link rel="stylesheet" href="/assets/css/style.css">
</head>

<body class="theme-blush">

<!-- Alerta de devolução pendente -->
<?php if (isset($this->view->devolucoesPendentes) && $this->view->devolucoesPendentes): ?>
    <div class="alert alert-warning alert-dismissible fade show" role="alert" id="alertadevolucao">
        <strong>Atenção!</strong> Há solicitações de devolução pendentes que precisam ser verificadas.
        <a href="/emprestimos">Ir para emprestimo</a>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php endif; ?>

<!-- Page Loader -->
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="m-t-30"><img class="zmdi-hc-spin" src="/assets/images/loader.svg" width="48" height="48" alt="Aero"></div>
        <p>Carregando...</p>
    </div>
</div>

<!-- Overlay For Sidebars -->
<div class="overlay"></div>
<!-- Left Sidebar -->
<aside id="leftsidebar" class="sidebar">
    <div class="navbar-brand">
        <button class="btn-menu ls-toggle-btn" type="button"><i class="zmdi zmdi-menu"></i></button>
        <a href="/administracao"><img src="/assets/images/logo.png " width="25" alt="Aero"><span class="m-l-10">Biblioteca</span></a>
    </div>
    <div class="menu">
        <ul class="list">
            <li>
                <div class="user-info">
                    <a class="pt-1" href="<?= $page ?>">
                        <div class="detail">
                            <h4 class="my-2 "><?= $_SESSION['nome'] ?></h4>
                            <small class="mt-3 mx-3"><?= $_SESSION['tipo_usuario'] ?></small>
                        </div>
                    </a>
                </div>
            </li>
                <li class="active open"><a href="/home"><i class="zmdi zmdi-home"></i><span>Home</span></a></li>
                <?php if ($_SESSION['tipo_usuario'] === 'gerente'): ?>
                    <li class="active open"><a href="/usuarios"><i class="zmdi zmdi-assignment-account"></i><span>Usuarios</span></a></li>
                <?php endif;?>
                <li class="active open"><a href="/livros"><i class="zmdi zmdi-library"></i><span>Livros</span></a></li>
                <li class="active open"><a href="/emprestimos"><i class="zmdi zmdi-mall"></i><span>Emprestimos</span></a></li>

        </ul>
    </div>
</aside>

            <?= $this->content() ?>

<!-- Jquery Core Js -->
<script src="/assets/bundles/libscripts.bundle.js"></script> <!-- Lib Scripts Plugin Js ( jquery.v3.2.1, Bootstrap4 js) -->
<script src="/assets/bundles/vendorscripts.bundle.js"></script> <!-- slimscroll, waves Scripts Plugin Js -->

<script src="/assets/plugins/jquery-inputmask/jquery.inputmask.bundle.js"></script> <!-- Input Mask Plugin Js -->
<script src="/assets/plugins/multi-select/js/jquery.multi-select.js"></script> <!-- Multi Select Plugin Js -->
<script src="/assets/plugins/jquery-spinner/js/jquery.spinner.js"></script> <!-- Jquery Spinner Plugin Js -->
<script src="/assets/plugins/bootstrap-tagsinput/bootstrap-tagsinput.js"></script> <!-- Bootstrap Tags Input Plugin Js -->
<script src="/assets/plugins/nouislider/nouislider.js"></script> <!-- noUISlider Plugin Js -->
<script src="/assets/js/pages/forms/advanced-form-elements.js"></script>

<script src="/assets/bundles/jvectormap.bundle.js"></script> <!-- JVectorMap Plugin Js -->
<script src="/assets/bundles/sparkline.bundle.js"></script> <!-- Sparkline Plugin Js -->
<script src="/assets/bundles/c3.bundle.js"></script>

<script src="/assets/bundles/mainscripts.bundle.js"></script>
<script src="/assets/js/pages/index.js"></script>
<script src="/assets/plugins/select2/select2.min.js"></script> <!-- Select2 Js -->
<script src="assets/js/pages/calendar/calendar.js"></script>
<script src="assets/bundles/fullcalendarscripts.bundle.js"></script><!--/ calender javascripts -->
<script src="/assets/js/pages/js.js"></script>


</body>
</html>