<?php
$page = basename($_SERVER['REQUEST_URI']);
?>

<!-- Main Content -->
<section class="content">
    <div class="body_scroll">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-7 col-md-6 col-sm-12">
                    <h2> <?= $page; ?> </h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="/home"><i class="zmdi zmdi-home"></i> Home</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="/livros"><i class="zmdi zmdi-library"></i> Livros</a>
                        </li>
                        <?php if ($_SERVER['REQUEST_URI'] == '/cadastrarlivro') : ?>
                            <li class="breadcrumb-item active">Cadastro de livros</li>
                        <?php endif; ?>
                    </ul>
                    <button class="btn btn-primary btn-icon mobile_menu" type="button"><i class="zmdi zmdi-sort-amount-desc"></i></button>
                </div>
                <div class="col-lg-5 col-md-6 col-sm-12">
                    <a href="/sair" class="mega-menu btn btn-danger btn-icon float-right" title="Sair"><i class="zmdi zmdi-power"></i></a>
                </div>
            </div>
        </div>
        <hr>
        <div class="container-fluid">
            <!-- Input -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card">
                        <div class="body">
                            <h2 class="card-inside-title">Cadastrar novo livro</h2>
                            <?php if ($this->view->erroCadastro) { ?>
                                <small class="form-text text-danger">*Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente.</small>
                            <?php } ?>
                                <div class="row clearfix">
                                    <div class="col-sm-12">
                                        <form action="/registrarlivro" method="post">
                                            <div class="form-group">
                                                <input type="text" class="form-control" name="titulo"  value="<?= $this->view->livros['titulo'] ?>" placeholder="Titulo" />
                                            </div>
                                            <div class="form-group">
                                                <input type="text" class="form-control" name="autor"  value="<?= $this->view->livros['autor'] ?>" placeholder="Autor" />
                                            </div>
                                            <div class="form-group">
                                                <input type="text" class="form-control" name="isbn"  value="<?= $this->view->livros['isbn'] ?>" placeholder="ISBN" />
                                            </div>
                                            <button type="button" onclick="document.querySelector('form').submit();" class="btn btn-success waves-effect">Cadastrar</button>
                                        </form>
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>