<?php
$page = basename($_SERVER['REQUEST_URI']);
$usuario = $_SESSION['id'];
?>


<!-- Main Content -->
<section class="content file_manager">
    <div class="body_scroll">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-7 col-md-6 col-sm-12">
                    <h2>Livros</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="/home"><i class="zmdi zmdi-home"></i> Home</a>
                        </li>
                        <?php if ($_SERVER['REQUEST_URI'] == '/livros' || $_SERVER['REQUEST_URI'] == '/registrarlivro') : ?>
                            <li class="breadcrumb-item active">Livros</li>
                        <?php endif; ?>
                    </ul>
                    <button class="btn btn-primary btn-icon mobile_menu" type="button"><i class="zmdi zmdi-sort-amount-desc"></i></button>
                </div>
                <div class="col-lg-5 col-md-6 col-sm-12">
                    <a href="/sair" class="mega-menu btn btn-danger btn-icon float-right" title="Sair"><i class="zmdi zmdi-power"></i></a>
                </div>
            </div>
        </div>
        <hr>
        <div class="container-fluid">
            <div class="row clearfix">
                <div class="col-lg-12">
                    <div class="card">
                        <?php if (isset($this->view->success) && $this->view->success) { ?>
                            <small class="form-text text-success font-13 font-weight-bold text-center alert-success"><?= $this->view->success ?></small>
                        <?php } ?>
                        <?php if (isset($this->view->error) && $this->view->error) { ?>
                            <small class="form-text text-danger font-13 font-weight-bold text-center alert-danger"><?= $this->view->error ?></small>
                        <?php } ?>
                        <ul class="nav nav-tabs pl-0 pr-0">
                            <?php if (in_array($_SESSION['tipo_usuario'], ['professor', 'gerente'])): ?>
                            <li class="nav-item"><a class="btn btn-success font-weight-bold font-13" href="/cadastrarlivro">
                                    <i class="zmdi zmdi-plus font-13 font-weight-bold"></i> Cadastrar</a>
                            </li>
                            <?php endif;?>
                            <li class="col-md-8">
                                <form method="GET" action="/livros" id="formpesquisa" class="mb-4">
                                    <div class="row justify-content-center align-items-center">
                                        <div class="col-md-8">
                                            <div class="input-group">
                                                <input  type="text"
                                                        name="pesquisar"
                                                        id="pesquisar"
                                                        class="form-control"
                                                        placeholder="Digite o titulo do livro"
                                                        aria-label="Pesquisar Livro">
                                                <div class="input-group-append">
                                                    <button type="submit"
                                                            class="btn btn-primary m-0"
                                                            onclick="document.getElementById('formpesquisa').submit();">
                                                        Buscar
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="doc">
                                <div class="row clearfix">
                                    <?php foreach ($this->view->livros as $indice => $livros) { ?>
                                    <div class="col-lg-3 col-md-4 col-sm-12">
                                            <div class="card">
                                                <div class="file">
                                                    <div class="hover">
                                                        <?php if (in_array($_SESSION['tipo_usuario'], ['professor', 'gerente'])): ?>
                                                            <form id="formexcluir-<?= $livros['id'] ?>" action="/deletarlivro/<?= $livros['id'] ?>" method="post">
                                                                <button type="button" class="btn btn-icon btn-icon-mini btn-round btn-danger"
                                                                        onclick="if (confirm('Certeza que deseja excluir o <?= $livros['titulo'] ?>?')) { document.getElementById('formexcluir-<?= $livros['id'] ?>').submit(); }">
                                                                    <i class="zmdi zmdi-delete"></i>
                                                                </button>
                                                            </form>
                                                        <?php endif;?>
                                                    </div>
                                                    <div class="icon">
                                                        <i class="zmdi zmdi-library"></i>
                                                    </div>
                                                    <div class="file-name">
                                                        <p class="m-b-5 text-muted"><?= $livros['titulo']?></p>
                                                        <small><?= $livros['autor']?> <span class="date text-muted"><?= $livros['isbn']?></span></small>

                                                        <?php if ($livros['disponivel']) : ?>
                                                                <strong class="text-success">Disponivel</strong>
                                                            <?php if ($_SESSION['tipo_usuario'] === 'gerente'):?>
                                                                <button class="btn btn-primary waves-effect" data-toggle="modal" data-target="#modalEmprestarLivro" data-id="<?= $livros['id'] ?>">
                                                                    Emprestar Livro
                                                                </button>
                                                            <?php else: ?>
                                                                <input type="hidden" name="usuarioSession" id="usuarioSession" value="<?= $usuario ?>">
                                                                <form method="POST" action="" id="formEmprestarsession">
                                                                </form>
                                                                <button class="btn btn-primary waves-effect" onclick="emprestarLivrosession(<?= $livros['id'] ?>)">
                                                                    Pegar Emprestado
                                                                </button>
                                                            <?php endif;?>
                                                        <?php else: ?>
                                                            <strong class="text-danger">Indisponivel</strong>
                                                        <?php endif; ?>

                                                    </div>
                                                </div>
                                            </div>
                                    </div>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<?php if ($_SESSION['tipo_usuario'] === 'gerente') :?>
<!-- Modal para empréstimo do livro -->
<div class="modal fade" id="modalEmprestarLivro" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="title" id="largeModalLabel">Lista de Usuários</h4>
            </div>
            <div class="modal-body">
                <span>Selecione o usuário que irá ficar com o livro.</span>
                <form method="POST" action="" id="formEmprestar">
                    <!-- Campo oculto para o ID do livro -->
                    <input type="hidden" name="livro_id" id="livro_id" value="<?= $livros['id'] ?>">
                    <div class="col-lg-8 col-md-6">
                        <div class="mb-3 mt-3">
                            <select class="form-control show-tick" data-live-search="true" name="usuario_id" id="usuarioSelect" required>
                                <option value="">Selecione um usuário</option>
                                <?php foreach ($this->view->usuario as $usuario) : ?>
                                    <option value="<?= $usuario['id'] ?>"><?= $usuario['nome'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <!-- Botão para submeter o formulário -->
                <button type="button" class="btn btn-default btn-round waves-effect" onclick="emprestarLivro()">Emprestar</button>
                <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>
<?php endif;?>

